<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-21T12:40:24 IST" name="Login Tests Suite" finished-at="2025-01-21T12:40:50 IST" duration-ms="26064">
    <groups>
    </groups>
    <test started-at="2025-01-21T12:40:24 IST" name="Login Test Cases" finished-at="2025-01-21T12:40:50 IST" duration-ms="26064">
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:24 IST" name="setUp" finished-at="2025-01-21T12:40:38 IST" duration-ms="13696" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initialize()[pri:0, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:38 IST" name="initialize" finished-at="2025-01-21T12:40:38 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="testValidLogin()[pri:1, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:38 IST" name="testValidLogin" finished-at="2025-01-21T12:40:42 IST" duration-ms="3917" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method signature="testInvalidLogin()[pri:2, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:42 IST" name="testInvalidLogin" finished-at="2025-01-21T12:40:50 IST" duration-ms="8110" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message not displayed for invalid login. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message not displayed for invalid login. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcases.LoginTest.testInvalidLogin(LoginTest.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method signature="testPasswordMasking()[pri:3, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:50 IST" name="testPasswordMasking" finished-at="2025-01-21T12:40:50 IST" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPasswordMasking -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.LoginTest@37afeb11]" started-at="2025-01-21T12:40:50 IST" name="tearDown" finished-at="2025-01-21T12:40:50 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Login Test Cases -->
  </suite> <!-- Login Tests Suite -->
</testng-results>
